### PR TITLE
Update for next school year

### PR DESCRIPTION
**Pull request by johnnyr26**
Just changed the text of the year to reflect the current school year we are about to head into.

### CODE REVIEW

**Review by jbis9051 — COMMENTED** [review]
I'm going to wait to merge until we are sure the scheduling system is staying the same. Due to COVID, if any of the scheduling systems that are being discussed are implemented we may want to support those changes.

**Comment by johnnyr26** [comment]
If there were a new schedule system, are you going to make the changes to this site or a different site?

Also should we just avoid using the years?

**Comment by jbis9051** [comment]
I'll make changes to this repo. I'll probably rework the entire design also. 

I think using the years confirms to users that it is up to date and current.

**Comment by jbis9051** [comment]
Basically:

If nothing regarding scheduling changes then I will merge this PR and that'll be it.

If there are changes, I will reorganize the project and change some things to make the code here not as horrible. Then we can work on implementing the new scheduling changes. 

Do you have experience working with React?

**Comment by johnnyr26** [comment]
I have some experience, but not too much. I'm more comfortable with node stuff. All of my projects at this point are private but I've been working with node for awhile. I can start reviewing React this and next week but I'm not sure if you're comfortable letting me do that. Why React?

**Comment by jbis9051** [comment]
React is a frontend framework. Makes working with frontend much easier. Depending on the changes needed, I may switch to react. I will probably use React hooks so focus on that. 

If you want to add me to the private repo's even as view only, I can give tips if you are interested.

**Comment by jbis9051** [comment]
I'll worry about the config stuff, but eventually you'll want to understand [webpack](https://webpack.js.org/), [babel](https://babeljs.io/).

**Comment by johnnyr26** [comment]
I have used babel so that won't be too much trouble for me. I'll do some exploring with web pack and React.

**Pull request closed without merging**
